wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [32, 32, 32, 32, 32]
    rows: [10, 10, 10, 10, 10, 10]
  refreshInterval: 30s
  mods:
    # first row
    devto:
      enabled: true
      numberOfArticles: 10
      position:
        top: 0
        left: 0
        height: 1
        width: 2
      # contentTag: "showdev"
      # contentState: "rising"
    feedreader:
      enabled: true
      feeds:
        - https://news.itsfoss.com/latest/rss/
      feedLimit: 10
      position:
        top: 0
        left: 2
        width: 3
        height: 1
      refreshInterval: 14400s

    # second row
    power:
      enabled: true
      position:
        top: 1
        left: 0
        height: 1
        width: 1
      refreshInterval: 15s
      title: "⚡️"
    ipinfo:
      colors:
        name: "lightblue"
        value: "white"
      enabled: true
      position:
        top: 1
        left: 1
        height: 1
        width: 2
      refreshInterval: 150s
    clocks:
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        Paris: "Europe/Paris"
        Dublin: "Europe/Dublin"
        New Dhelia: "Asia/Kolkata"
      position:
        top: 1
        left: 3
        height: 1
        width: 2
      refreshInterval: 15s
      sort: "alphabetical"
      title: "Clocks"
      type: "clocks"

    # third row (height 2)
    weather:
      title: "🌈"
      args: ["-d", "1"]
      cmd: "wego"
      enabled: true
      type: "cmdrunner"
      position:
        top: 2
        left: 0
        height: 2
        width: 4
      refreshInterval: 1h
    security:
      enabled: true
      position:
        top: 2
        left: 4
        height: 2
        width: 1
      refreshInterval: 1h

    # fourth row
    docker:
      type: docker
      enabled: true
      labelColor: lightblue
      position:
        top: 4
        left: 0
        height: 3
        width: 1
      refreshInterval: 1s
