wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [32, 32, 32, 32, 32]
    rows: [4, 10, 10, 10, 10, 10]
  refreshInterval: 30s
  mods:
    uptime:
      # args: [""]
      cmd: "uptime"
      enabled: true
      position:
        top: 0
        left: 0
        height: 1
        width: 3
      refreshInterval: 30s
      type: cmdrunner
    clocks:
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        Paris: "Europe/Paris"
        Dublin: "Europe/Dublin"
        New Dhelia: "Asia/Kolkata"
      position:
        top: 0
        left: 3
        height: 1
        width: 2
      refreshInterval: 15s
      sort: "alphabetical"
      title: "Clocks"
      type: "clocks"
    feedreader:
      enabled: true
      feeds:
        - http://feeds.bbci.co.uk/news/rss.xml
      feedLimit: 10
      position:
        top: 1
        left: 0
        width: 2
        height: 1
      refreshInterval: 14400s
    ipinfo:
      colors:
        name: "lightblue"
        value: "white"
      enabled: true
      position:
        top: 1
        left: 3
        height: 1
        width: 2
      refreshInterval: 150s
    power:
      enabled: true
      position:
        top: 1
        left: 2
        height: 1
        width: 1
      refreshInterval: 15s
      title: "⚡️"
    weather:
      # args: [""]
      cmd: "wego"
      enabled: true
      type: "cmdrunner"
      position:
        top: 2
        left: 0
        height: 3
        width: 4
      refreshInterval: 1h
    security:
      enabled: true
      position:
        top: 2
        left: 4
        height: 2
        width: 1
      refreshInterval: 1h
