version = "1.1.14"

[format]
dedup = true
dedup_inactive_fullscreen = false
delim = " "
client = "{icon}"
client_active = "<span color='red'>{icon}</span>"
workspace = "{id}:{delim}{clients}"
workspace_empty = "{id}"
client_dup = "{icon}{counter_sup}{delim}"
client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused_sup}"
client_fullscreen = "[{icon}]{delim}"

[class_active]
DEFAULT = "{icon}"
"(?i)firefox" = "<span color='orange'> {class}</span>"

# [initial_class]
# "DEFAULT" = " {class}: {title}"
# "(?i)Kitty" = "term"

# [initial_class_active]
# "(?i)Kitty" = "*TERM*"

# regex captures support is supported
[title_in_class."(?i)foot"]
"emerge: (.+?/.+?)-.*" = "{match1}"

[initial_title_in_class."kitty"]
"zsh" = "Zsh"

[title_in_class."(firefox|chrom.*)"]
"(?i)youtube" = "ꟳ"
"(?i)twitch" = "ꟳ"

[title_active."(firefox|chrom.*)"]
"(?i)twitch" = "<span color='purple'>{icon}</span>"

[class]
DEFAULT = ""
"(?i)firefox" = "<span color='orange'> </span>"
"(?i)kitty" = ""
Brave-browser = "󰢏"
bleachbit = ""
burp-startburp = ""
calibre-gui = ""
chromium = ""
"Gimp-2.10" = ""
code-oss = "󰨞"
'/zsh/' = ''
darktable = ""
discord = ""
dmenu-clipboard = ""
dmenu-pass = ""
duolingo = ""
element = ""
fontforge = ""
gcr-prompter = ""
gsimplecalc = ""
"kak" = ""
kicad = ""
"(?i)waydroid.*" = "droid"
"dmenu-emoji" = ""
"dmenu-browser" = ""
"dmenu-pass generator" = ""
"qalculate-gtk" = ""
libreoffice-calc = ""
libreoffice-impress = ""
libreoffice-startcenter = ""
libreoffice-writer = ""
mpv = ""
neomutt = ""
nm-connection-editor = ""
org-ksnip-ksnip = ""
org-pwmt-zathura = ""
org-telegram-desktop = ""
paperwork = ""
pavucontrol = ""
plexamp = ""
rapid-photo-downloader = ""
remote-viewer = ""
sandboxed-tor-browser = ""
scli = ""
slack = ""
snappergui = ""
songrec = ""
spotify = ""
steam = ""
streamlink-twitch-gui = ""
sun-awt-x11-xframepeer = ""
swappy = ""
taskwarrior-tui = ""
".*transmission.*" = ""
udiskie = ""
vimiv = ""
virt-manager = ""
vlc = ""
vncviewer = ""
wayvnc = "󰀄"
wire = "󰁀"
wireshark-gtk = ""
wlfreerdp = "󰀄"
work = ""
xplr = ""
nemo = ""
zoom = ""

[exclude]
"" = "^$" # prevent displaying clients with empty class
