return {
	"m4xshen/hardtime.nvim",
	event = "VeryLazy",
	-- enabled = false,
	opts = {
		max_time = 1000,
		max_count = 5,
		disable_mouse = false,
		hint = true,
		notification = true,
		allow_different_key = false,
		resetting_keys = {
			["1"] = { "n", "x" },
			["2"] = { "n", "x" },
			["3"] = { "n", "x" },
			["4"] = { "n", "x" },
			["5"] = { "n", "x" },
			["6"] = { "n", "x" },
			["7"] = { "n", "x" },
			["8"] = { "n", "x" },
			["9"] = { "n", "x" },
			["c"] = { "n" },
			["C"] = { "n" },
			["d"] = { "n" },
			["x"] = { "n" },
			["X"] = { "n" },
			["y"] = { "n" },
			["Y"] = { "n" },
			["p"] = { "n" },
			["P"] = { "n" },
		},
		restricted_keys = {
			-- ["h"] = { "n", "v" },
			["j"] = { "n", "v" },
			["k"] = { "n", "v" },
			-- ["l"] = { "n", "v" },
			["-"] = { "n", "v" },
			["+"] = { "n", "v" },
			["gj"] = { "n", "v" },
			["gk"] = { "n", "v" },
			["<CR>"] = { "n", "v" },
			["<C-M>"] = { "n", "v" },
			["<C-N>"] = { "n", "v" },
			["<C-P>"] = { "n", "v" },
		},
		disabled_keys = {
			["<UP>"] = { "", "i" },
			["<DOWN>"] = { "", "i" },
			["<LEFT>"] = { "", "i" },
			["<RIGHT>"] = { "", "i" },
		},
		disabled_filetypes = { "qf", "netrw", "neo-tree", "lazy", "mason" },
	},
}
