# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[aws]
format = 'on [$symbol$profile]($style) '

[custom.chezmoi]
description = "The current chezmoi status"
symbol = ' '
# format = 'at [$symbol$output]($style)'
format = '- [$symbol](bold purple)[\[!\]](bold red) '
# command = 'echo $(chezmoi status $PWD | wc -l)'
# when = ''' [ $(chezmoi managed $PWD | wc -l) -gt  0 ] '''
when = ''' ! chezmoi verify '''
